# Generated by Django 2.2.17 on 2021-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0035_remove_agrifield_name_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="croptype",
            name="custom",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Indicates whether this is the basis for customized crop types. "
                    "Only one crop type can be custom."
                ),
            ),
        ),
        migrations.AddField(
            model_name="agrifield",
            name="custom_parameter_set_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text=(
                    "Optional; it can help you remember why you customized the "
                    "parameters."
                ),
            ),
        ),
        migrations.AlterModelOptions(
            name="croptype",
            options={
                "ordering": ("custom", "name"),
                "verbose_name_plural": "Crop Types",
            },
        ),
    ]
