# Generated by Django 2.2.17 on 2021-02-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0036_custom_crop_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agrifield",
            options={
                "ordering": ("name", "wetted_area"),
                "verbose_name_plural": "Agrifields",
            },
        ),
        migrations.RenameField(
            model_name="agrifield",
            old_name="area",
            new_name="wetted_area",
        ),
    ]
