# Generated by Django 3.2 on 2021-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0038_is_virtual_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fathers_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Father's name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone number"
            ),
        ),
    ]
