# Generated by Django 3.2 on 2021-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0039_user_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="agrifield",
            name="code",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Field code"
            ),
        ),
        migrations.AddField(
            model_name="agrifield",
            name="hydrant",
            field=models.CharField(
                blank=True,
                help_text="The number of the hydrant from which the field is irrigated",
                max_length=30,
                verbose_name="Hydrant",
            ),
        ),
        migrations.AddField(
            model_name="agrifield",
            name="irrigated_area",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Irrigated area"
            ),
        ),
        migrations.AddField(
            model_name="agrifield",
            name="no_code",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If the field has an unknown code, or if it is unknown whether it "
                    "has a code, leave this off and the code blank."
                ),
                verbose_name="Field does not have a code",
            ),
        ),
        migrations.AddField(
            model_name="agrifield",
            name="total_area",
            field=models.FloatField(blank=True, null=True, verbose_name="Total area"),
        ),
        migrations.AddIndex(
            model_name="agrifield",
            index=models.Index(
                condition=models.Q(_negated=True, code=""),
                fields=["code"],
                name="code_unique",
            ),
        ),
    ]
