# Generated by Django 3.2 on 2021-05-14 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0041_alter_appliedirrigation_supplied_water_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedirrigation",
            name="supplied_flow_rate",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "If empty, an automatically calculated default will be assumed"
                ),
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Flow rate (m3/h)",
            ),
        ),
    ]
